//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./ServiceContract_types');
//HELPER FUNCTIONS AND STRUCTURES

var MyThriftService_GetSum_args = function(args) {
  this.num1 = null;
  this.num2 = null;
  if (args) {
    if (args.num1 !== undefined && args.num1 !== null) {
      this.num1 = args.num1;
    }
    if (args.num2 !== undefined && args.num2 !== null) {
      this.num2 = args.num2;
    }
  }
};
MyThriftService_GetSum_args.prototype = {};
MyThriftService_GetSum_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.DOUBLE) {
        this.num1 = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.DOUBLE) {
        this.num2 = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MyThriftService_GetSum_args.prototype.write = function(output) {
  output.writeStructBegin('MyThriftService_GetSum_args');
  if (this.num1 !== null && this.num1 !== undefined) {
    output.writeFieldBegin('num1', Thrift.Type.DOUBLE, 1);
    output.writeDouble(this.num1);
    output.writeFieldEnd();
  }
  if (this.num2 !== null && this.num2 !== undefined) {
    output.writeFieldBegin('num2', Thrift.Type.DOUBLE, 2);
    output.writeDouble(this.num2);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var MyThriftService_GetSum_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
MyThriftService_GetSum_result.prototype = {};
MyThriftService_GetSum_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.DOUBLE) {
        this.success = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MyThriftService_GetSum_result.prototype.write = function(output) {
  output.writeStructBegin('MyThriftService_GetSum_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.DOUBLE, 0);
    output.writeDouble(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var MyThriftService_GetHelloMessage_args = function(args) {
  this.name = null;
  if (args) {
    if (args.name !== undefined && args.name !== null) {
      this.name = args.name;
    }
  }
};
MyThriftService_GetHelloMessage_args.prototype = {};
MyThriftService_GetHelloMessage_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MyThriftService_GetHelloMessage_args.prototype.write = function(output) {
  output.writeStructBegin('MyThriftService_GetHelloMessage_args');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var MyThriftService_GetHelloMessage_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
MyThriftService_GetHelloMessage_result.prototype = {};
MyThriftService_GetHelloMessage_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MyThriftService_GetHelloMessage_result.prototype.write = function(output) {
  output.writeStructBegin('MyThriftService_GetHelloMessage_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var MyThriftService_OpenWindow_args = function(args) {
  this.title = null;
  if (args) {
    if (args.title !== undefined && args.title !== null) {
      this.title = args.title;
    }
  }
};
MyThriftService_OpenWindow_args.prototype = {};
MyThriftService_OpenWindow_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.title = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MyThriftService_OpenWindow_args.prototype.write = function(output) {
  output.writeStructBegin('MyThriftService_OpenWindow_args');
  if (this.title !== null && this.title !== undefined) {
    output.writeFieldBegin('title', Thrift.Type.STRING, 1);
    output.writeString(this.title);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var MyThriftService_OpenWindow_result = function(args) {
};
MyThriftService_OpenWindow_result.prototype = {};
MyThriftService_OpenWindow_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MyThriftService_OpenWindow_result.prototype.write = function(output) {
  output.writeStructBegin('MyThriftService_OpenWindow_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var MyThriftServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
MyThriftServiceClient.prototype = {};
MyThriftServiceClient.prototype.seqid = function() { return this._seqid; };
MyThriftServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

MyThriftServiceClient.prototype.GetSum = function(num1, num2, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetSum(num1, num2);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetSum(num1, num2);
  }
};

MyThriftServiceClient.prototype.send_GetSum = function(num1, num2) {
  var output = new this.pClass(this.output);
  var params = {
    num1: num1,
    num2: num2
  };
  var args = new MyThriftService_GetSum_args(params);
  try {
    output.writeMessageBegin('GetSum', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

MyThriftServiceClient.prototype.recv_GetSum = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MyThriftService_GetSum_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetSum failed: unknown result');
};

MyThriftServiceClient.prototype.GetHelloMessage = function(name, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetHelloMessage(name);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetHelloMessage(name);
  }
};

MyThriftServiceClient.prototype.send_GetHelloMessage = function(name) {
  var output = new this.pClass(this.output);
  var params = {
    name: name
  };
  var args = new MyThriftService_GetHelloMessage_args(params);
  try {
    output.writeMessageBegin('GetHelloMessage', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

MyThriftServiceClient.prototype.recv_GetHelloMessage = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MyThriftService_GetHelloMessage_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetHelloMessage failed: unknown result');
};

MyThriftServiceClient.prototype.OpenWindow = function(title, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_OpenWindow(title);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_OpenWindow(title);
  }
};

MyThriftServiceClient.prototype.send_OpenWindow = function(title) {
  var output = new this.pClass(this.output);
  var params = {
    title: title
  };
  var args = new MyThriftService_OpenWindow_args(params);
  try {
    output.writeMessageBegin('OpenWindow', Thrift.MessageType.ONEWAY, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    this.output.flush();
    var callback = this._reqs[this.seqid()] || function() {};
    delete this._reqs[this.seqid()];
    callback(null);
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};
var MyThriftServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
MyThriftServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
MyThriftServiceProcessor.prototype.process_GetSum = function(seqid, input, output) {
  var args = new MyThriftService_GetSum_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetSum.length === 2) {
    Q.fcall(this._handler.GetSum.bind(this._handler),
      args.num1,
      args.num2
    ).then(function(result) {
      var result_obj = new MyThriftService_GetSum_result({success: result});
      output.writeMessageBegin("GetSum", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("GetSum", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.GetSum(args.num1, args.num2, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new MyThriftService_GetSum_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("GetSum", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetSum", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
MyThriftServiceProcessor.prototype.process_GetHelloMessage = function(seqid, input, output) {
  var args = new MyThriftService_GetHelloMessage_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetHelloMessage.length === 1) {
    Q.fcall(this._handler.GetHelloMessage.bind(this._handler),
      args.name
    ).then(function(result) {
      var result_obj = new MyThriftService_GetHelloMessage_result({success: result});
      output.writeMessageBegin("GetHelloMessage", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("GetHelloMessage", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.GetHelloMessage(args.name, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new MyThriftService_GetHelloMessage_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("GetHelloMessage", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetHelloMessage", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
MyThriftServiceProcessor.prototype.process_OpenWindow = function(seqid, input, output) {
  var args = new MyThriftService_OpenWindow_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.OpenWindow(args.title);
};
